### ISSUE TITLE
[BUG] Index out of bounds when deleting object p0

### ISSUE THREAD

**Issue by MetaverseRPN** [DaIsimsiz/AR-planetDef-Builder#2]
This error occurs when attempting to delete object p0, which appears to be the vanilla/default Sol object.
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at ARplanetDefBuilder.Program.AnalyzeInput(String input) in C:\Users\[REDACTED]\Desktop\Repos\1.12.2-Console\Program.cs:line 162
   at ARplanetDefBuilder.Program.Main() in C:\Users\[REDACTED]\Desktop\Repos\1.12.2-Console\Program.cs:line 34

**Comment by DaIsimsiz** [comment]
oof, this is very embarassing, i think i know the cause

**Comment by DaIsimsiz** [comment]
I'm making sure .Net 7 gets installed automatically, but I first need to uninstall it on my slow computer :') I will post an update once I am done with this.

**Comment by DaIsimsiz** [comment]
May I ask you to run a different version? I assume you've kept your .NET 7 runtime, so I think this should work, the version you had was referencing files on my own computer (stupid mistake)

First, just extract the files inside `publish` folder.
If it doesn't work, try all of the files in the zip.

[test.zip](https://github.com/DaIsimsiz/AR-planetDef-Builder/files/13588955/test.zip)

**Comment by MetaverseRPN** [comment]
I'll give it a try for you now.

**Comment by MetaverseRPN** [comment]
Same error in the files outside the publish folder as well.

**Comment by DaIsimsiz** [comment]
What throws me off-course and confuses the HECK outta me is the fact that it shows you MY OWN directories..?

It's not supposed to show you errors **I** would see, but this is indeed an actual bug instead of an installation error.

**Comment by MetaverseRPN** [comment]
Sure

**Comment by DaIsimsiz** [comment]
So it does what it's supposed to properly, but it continues with the code, because I forgot an "else" in front of the "if" statement.
And checked the 5th letter in "y" which was... out of bounds.

**Comment by DaIsimsiz** [comment]
I could not find a way to easily install .NET 7 with the program, so I will just pack the installer with the app :')
