### ISSUE TITLE
crash while creating gasgiant

### ISSUE THREAD

**Issue by DiamondMiner1** [DaIsimsiz/AR-planetDef-Builder#5]
**Describtion**
I tried creating a gasgiant to my star.
when i came to the question wich gas it should contain,
i typed in "nitrogen".
after entering the command, the program closed itself
(most likely a crash)

**To Reproduce**
1. create a gas giant
2. when come to the question wich gas, then type in "nitrogen"
3. The program should close itself after entering the command

**Expected behavior**
a simple creation of the gasgiant i typed in

**Screenshots**
- none available due to it being a crash -

**Comment by DaIsimsiz** [comment]
The problem has been identified:
The code never checks if the value of the attribute it is trying to modify exists.
For simplicity, adding, removing, and changing value are made to be the same thing.
A check is being added.

**Comment by DaIsimsiz** [comment]
There was also a "bit more" going on after that problem. That's been dealt with now.
