### ISSUE TITLE
trapped when adding property

### ISSUE THREAD

**Issue by DiamondMiner1** [DaIsimsiz/AR-planetDef-Builder#7]
**Describe the bug**
When trying to add a property to a planet
(tried to add rings)
then you are trapped in that menu when you have no option
i recommend adding a function, that when you type smth like
/back 
you go back in the menu

**To Reproduce**
1. create planet
2. edit planet
3. type in "new property"
4. you should now be trapped in that menu

**Expected behavior**
a possible way going back

**Screenshots**
are attached to the report
![Bild_2024-01-06_034252719](https://github.com/DaIsimsiz/AR-planetDef-Builder/assets/131694483/b2ea2ee1-fed2-4429-b305-f2b43c5527ba)

**Comment by DaIsimsiz** [comment]
This issue is related to issue #6 in a way. This should be easy to fix.
Once again, the fix will be pushed with the next release.

**Comment by DaIsimsiz** [comment]
You will no longer be able to attempt to add properties if there are no more to add, and on top of that, entering no text will cancel the process.
