### ISSUE TITLE
Add a texture selector

### ISSUE THREAD

**Issue by DiamondMiner1** [DaIsimsiz/AR-planetDef-Builder#8]
**Is your feature request related to a problem? Please describe.**
there isn't a selection option for the planet/gasgiant texture

**Describe the solution you'd like**
A simple question that asks what texture you want
the question could accept all names from the wiki

**Comment by DaIsimsiz** [comment]
You can add a `customIcon` attribute with either the path or name of the icon you want. This is currently inaccessible due to issues #5 #6 #7, try again when the next release is pushed which *is* taking longer than expected.
But be assured that I **am** working on it without break!
