### ISSUE TITLE
export failing/"planetdef" not working

### ISSUE THREAD

**Issue by DiamondMiner1** [DaIsimsiz/AR-planetDef-Builder#9]
**Describe the bug**
Bug1
This one is kind of mixed.
On the one side, it isn't possible to export planetDefs
The Program gives 2 error messages, and then closes itself.

Bug2(?)
i found out, that the program has a backup, wich looked like a planetDef
i renamed it, and imported it into minecraft.
The world i create crashes 1 Second after i see the first blocks.
This is due to a "exception of server tick loop"
the crash report shows something with the planet file
it says creating planet, but repeats the same message again and again.

**To Reproduce**
1. make a file with the editor
2. try exporting it
3. Program will crash, with no planetDef available

**To Reproduce**
1. Take the planetDef and create a world with it
4. The world should crash immidiently after creation.

**Expected behavior**
typing export and file exports without problems
/
Creating world, with no crash and seeing the planets

**Screenshots**
None available
Minecraft crashes, and the Editor closes itself

The Crash Report and planetDef (changed to .txt due to Github not supporting .XML) should be attached to this

[crash-2024-01-07_05.20.13-server.txt](https://github.com/DaIsimsiz/AR-planetDef-Builder/files/13852255/crash-2024-01-07_05.20.13-server.txt)

[planetDef.txt](https://github.com/DaIsimsiz/AR-planetDef-Builder/files/13852259/planetDef.txt)

**Comment by DaIsimsiz** [comment]
Reading the files led me to believe that the latter is caused by incorrect values for fields, such as "0.5,1.0" for fog color when there should always be 3 values

But I will investigate the former
And take fixing the latter into consideration.

**Comment by DaIsimsiz** [comment]
The file you used was the auto-save I implemented after seeing so many crash bugs.
You can literally reopen the app and load the file to continue editing the file.
Unless that is broken too...

**Comment by DaIsimsiz** [comment]
The former problem was caused by the method which I used to get a valid appdata failing to realize that an empty file is NOT valid data, and sending me an empty data...
Which would cause values I look up to not exist, hence the NullReferenceException's
I added another layer of protection to combat this.

The original bug report is fixed, but I will try to fix your planetDefs file too.
